name: Going Postal
favicon: null
layout_spectrum: 0.09263853169977665
typography_spectrum: 0.271934523480013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f8fd'
    - '#1f1f1f'
    - '#d3b08d'
    - '#b93354'
    - '#1f7ec3'
  brandStrength: 0.6875
  lightness: 0.3649675496853888
  saturation: 0.25
  rhythmicContrast: 0.4635073165409267
purpose: []
